price-multiplier: 1.5

default-labels:
  - "Time: <1 Hour"
  - "Priority: 1 (Normal)"
time-labels:
  - name: "Time: <1 Hour"
    weight: 0.125
    value: 3600
    extra: "make it invalid"
  - name: "Time: <1 Day"
    weight: 1
    value: 86400
  - name: "Time: <1 Week"
    weight: 2
    value: 604800
  - name: "Time: <2 Weeks"
    weight: 3
    value: 1209600
  - name: "Time: <1 Month"
    weight: 4
    value: 2592000
someOther: "what"
